### ISSUE TITLE
problem with connection to redis cluster from macOS. Python config/version related?

### ISSUE THREAD

**Issue by valery-zhurbenko** [talkiq/redis-cli-cluster#4]
```
Valerys-MacBook-Pro:~ valeryzhurbenko$ redis-cli-cluster  -h colucache-qa.colu.co -p 6379
Traceback (most recent call last):
  File "/usr/local/bin/redis-cli-cluster", line 11, in <module>
    load_entry_point('redis-cli-cluster==0.6.1', 'console_scripts', 'redis-cli-cluster')()
  File "/usr/local/lib/python3.6/site-packages/redis_cli_cluster-0.6.1-py3.6.egg/redis_cli_cluster/__main__.py", line 29, in main
  File "/usr/local/lib/python3.6/site-packages/redis_cli_cluster-0.6.1-py3.6.egg/redis_cli_cluster/cluster.py", line 11, in __init__
  File "/usr/local/lib/python3.6/site-packages/redis_py_cluster-1.3.4-py3.6.egg/rediscluster/client.py", line 181, in __init__
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/redis_py_cluster-1.3.4-py3.6.egg/rediscluster/connection.py", line 141, in __init__
    self.nodes.initialize()
  File "/usr/local/lib/python3.6/site-packages/redis_py_cluster-1.3.4-py3.6.egg/rediscluster/nodemanager.py", line 228, in initialize
    need_full_slots_coverage = self.cluster_require_full_coverage(nodes_cache)
  File "/usr/local/lib/python3.6/site-packages/redis_py_cluster-1.3.4-py3.6.egg/rediscluster/nodemanager.py", line 270, in cluster_require_full_coverage
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/usr/local/lib/python3.6/site-packages/redis_py_cluster-1.3.4-py3.6.egg/rediscluster/nodemanager.py", line 270, in <genexpr>
    return any(node_require_full_coverage(node) for node in nodes.values())
  File "/usr/local/lib/python3.6/site-packages/redis_py_cluster-1.3.4-py3.6.egg/rediscluster/nodemanager.py", line 267, in node_require_full_coverage
    return "yes" in r_node.config_get("cluster-require-full-coverage").values()
  File "/usr/local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 715, in config_get
    return self.execute_command('CONFIG GET', pattern)
  File "/usr/local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis-2.10.6-py3.6.egg/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'CONFIG'
```

From regular clean linux with python 3.4 all works perfect.

**Comment by TheKevJames** [comment]
Huh, looks like that error is being spawned by the `redis-py-cluster` project.

Which version of Python are you using?

Could you please run the following (in your Python interpreter, run it with `python3`) and post the response:

```
import rediscluster
rediscluster.StrictRedisCluster(host='colucache-qa.colu.co', port='6379', decode_responses=True)
```
